version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Zurich
    open-pull-requests-limit: 5
    groups:
      production-patches:
        dependency-type: production
        update-types:
          - patch
      development-patches:
        dependency-type: development
        update-types:
          - patch
